package com.efe13.reader.excel;

import java.util.ArrayList;
import java.util.List;

public class PopulationsCollection {

	private List<String> list = new ArrayList<String>();
	
	public PopulationsCollection() {
		list.add( "ACÁMBARO" );
		list.add( "ACAPONETA Y TECUALA" );
		list.add( "ACAPULCO" );
		list.add( "ACATLÁN DE PÉREZ FIGUEROA" );
		list.add( "ADIVINO" );
		list.add( "AGUA PRIETA" );
		list.add( "AGUALEGUAS" );
		list.add( "AGUASCALIENTES" );
		list.add( "ÁLAMOS" );
		list.add( "ALTZOMONI" );
		list.add( "ANÁHUAC" );
		list.add( "APATZINGÁN" );
		list.add( "APIZACO" );
		list.add( "ARAMBERRI" );
		list.add( "ARIVECHI" );
		list.add( "ARIZPE" );
		list.add( "ARMERÍA" );
		list.add( "ARRIAGA" );
		list.add( "ARRIAGA - TONALÁ" );
		list.add( "ASUNCIÓN  NOCHISTLAN" );
		list.add( "ATARJEA" );
		list.add( "ATIL" );
		list.add( "ATOTONILCO EL ALTO" );
		list.add( "AUTLÁN DE NAVARRO" );
		list.add( "BACADEHUACHI" );
		list.add( "BACANORA" );
		list.add( "BACERAC" );
		list.add( "BACOACHI" );
		list.add( "BAHÍA ASUNCIÓN" );
		list.add( "BAHÍA DE TORTUGAS" );
		list.add( "BANAMICHI" );
		list.add( "BAVIACORA" );
		list.add( "BAVISPE" );
		list.add( "BENEMÉRITO DE LAS AMÉRICAS" );
		list.add( "BENJAMÍN HILL" );
		list.add( "CABORCA" );
		list.add( "CADEREYTA-MONTERREY" );
		list.add( "CALPULALPAN" );
		list.add( "CALVILLO" );
		list.add( "CAMPECHE" );
		list.add( "CANANEA" );
		list.add( "CANCÚN" );
		list.add( "CARBO" );
		list.add( "CD. ACUÑA" );
		list.add( "CD. ALLENDE" );
		list.add( "CD. CAMARGO" );
		list.add( "CD. CONSTITUCIÓN" );
		list.add( "CD. CUAUHTÉMOC" );
		list.add( "CD. DEL CARMEN" );
		list.add( "CD. DELICIAS" );
		list.add( "CD. GUZMÁN" );
		list.add( "CD. HIDALGO" );
		list.add( "CD. JIMÉNEZ" );
		list.add( "CD. JUÁREZ" );
		list.add( "CD. MADERA" );
		list.add( "CD. MANTE" );
		list.add( "CD. OBREGÓN" );
		list.add( "CD. VALLES" );
		list.add( "CD. VICTORIA" );
		list.add( "CELAYA" );
		list.add( "CERRALVO-MELCHOR OCAMPO" );
		list.add( "CERRO AZUL" );
		list.add( "CERRO LOS TENAMASTES" );
		list.add( "CERRO PICO TRES PADRES" );
		list.add( "CHETUMAL" );
		list.add( "CHIHUAHUA" );
		list.add( "CHILPANCINGO" );
		list.add( "CINTALAPA DE FIGUEROA" );
		list.add( "COATZACOALCOS" );
		list.add( "COLIMA" );
		list.add( "COMITÁN DE DOMÍNGUEZ" );
		list.add( "COMONFORT" );
		list.add( "CONCEPCIÓN PÁPALO" );
		list.add( "CORONEO" );
		list.add( "CORRAL DE PIEDRA" );
		list.add( "COZUMEL" );
		list.add( "CUCURPE" );
		list.add( "CUENCAME" );
		list.add( "CUERNAVACA" );
		list.add( "CULIACÁN" );
		list.add( "CUMPAS" );
		list.add( "DIVISADERO" );
		list.add( "DOLORES HIDALGO" );
		list.add( "DR. ARROYO" );
		list.add( "DR. COSS" );
		list.add( "DR. MORA" );
		list.add( "DURANGO" );
		list.add( "EL TRIUNFO" );
		list.add( "ENSENADA" );
		list.add( "ESCÁRCEGA" );
		list.add( "FELIPE CARRILLO PUERTO" );
		list.add( "FRESNILLO" );
		list.add( "FRONTERA" );
		list.add( "FRONTERAS" );
		list.add( "GÓMEZ PALACIO" );
		list.add( "GRAL. BRAVO-GRAL. TAPIA" );
		list.add( "GRAL. TREVIÑO" );
		list.add( "GRANADOS" );
		list.add( "GUADALAJARA" );
		list.add( "GUADALUPE VICTORIA" );
		list.add( "GUANAJUATO" );
		list.add( "GUAYMAS" );
		list.add( "GUERRERO NEGRO" );
		list.add( "HERMOSILLO" );
		list.add( "HIDALGO DEL PARRAL" );
		list.add( "HIGUERAS" );
		list.add( "HUACHINERAS" );
		list.add( "HUAJUAPAN DE LEÓN" );
		list.add( "HUAMANTLA" );
		list.add( "HUANÍMARO" );
		list.add( "HUASABAS" );
		list.add( "HUAUTLA DE JIMÉNEZ" );
		list.add( "HUAYACOCOTLA" );
		list.add( "HUEJUTLA DE REYES" );
		list.add( "IGUALA" );
		list.add( "IMURIS" );
		list.add( "ISLA DE CEDROS" );
		list.add( "ISLA SOCORRO" );
		list.add( "ISLAS MARÍAS" );
		list.add( "ITURBIDE" );
		list.add( "IXHUATLAN DE MADERO" );
		list.add( "IXMIQUILPAN" );
		list.add( "IXTAPA-ZIHUATANEJO" );
		list.add( "JALPA" );
		list.add( "JERÉCUARO" );
		list.add( "JIQUILPAN DE JUÁREZ" );
		list.add( "JOCOTITLAN" );
		list.add( "JUCHITÁN DE ZARAGOZA" );
		list.add( "LA BARCA" );
		list.add( "LA CHONA- ARAMBERRI" );
		list.add( "LA PAZ" );
		list.add( "LA PIEDAD" );
		list.add( "LA ROSITA - VILLAGRÁN" );
		list.add( "LA VENTA" );
		list.add( "LAMPAZOS" );
		list.add( "LAS LAJAS" );
		list.add( "LÁZARO CÁRDENAS" );
		list.add( "LEÓN" );
		list.add( "LINARES" );
		list.add( "LOMA BONITA" );
		list.add( "LOS ALDAMAS-ESTACIÓN LOS ALDAMA" );
		list.add( "LOS HERRERA" );
		list.add( "LOS MOCHIS" );
		list.add( "LOS RAMONES" );
		list.add( "LOS REYES SALGADO" );
		list.add( "MAGDALENA DE KINO" );
		list.add( "MANZANILLO" );
		list.add( "MARQUES DE COMILLAS" );
		list.add( "MATAMOROS" );
		list.add( "MATEHUALA" );
		list.add( "MATÍAS ROMERO" );
		list.add( "MAZATAN" );
		list.add( "MAZATLÁN" );
		list.add( "MECAYAPAN" );
		list.add( "MERIDA" );
		list.add( "MEXICALI" );
		list.add( "MÉXICO" );
		list.add( "MIAHUATLÁN" );
		list.add( "MIER Y NORIEGA" );
		list.add( "MOCTEZUMA " );
		list.add( "MONCLOVA" );
		list.add( "MONTERREY" );
		list.add( "MORELIA" );
		list.add( "MOTOZINTLA" );
		list.add( "NACO" );
		list.add( "NACORI CHICO" );
		list.add( "NACORI GRANDE" );
		list.add( "NACOZARI" );
		list.add( "NAVOJOA" );
		list.add( "NOCHISTLÁN" );
		list.add( "NOGALES" );
		list.add( "NUEVA ROSITA" );
		list.add( "NUEVO CASAS GRANDES" );
		list.add( "NUEVO LAREDO" );
		list.add( "OAXACA" );
		list.add( "OCAMPO" );
		list.add( "OCOSINGO" );
		list.add( "OJINAGA" );
		list.add( "OMETEPEC" );
		list.add( "ONAVAS" );
		list.add( "OQUITOA" );
		list.add( "ORIZABA" );
		list.add( "PACHUCA" );
		list.add( "PALENQUE" );
		list.add( "PALMA SOLA" );
		list.add( "PARAS" );
		list.add( "PARRAS DE LA FUENTE" );
		list.add( "PÁTZCUARO" );
		list.add( "PÉNJAMO" );
		list.add( "PEROTE" );
		list.add( "PICHUCALCO" );
		list.add( "PIEDRAS NEGRAS" );
		list.add( "PIJIJIAPAN" );
		list.add( "PUEBLA" );
		list.add( "PUERTO ÁNGEL" );
		list.add( "PUERTO ESCONDIDO" );
		list.add( "PUERTO PEÑASCO" );
		list.add( "PUERTO VALLARTA" );
		list.add( "PURUANDIRO" );
		list.add( "QUERÉTARO" );
		list.add( "QUEROBABI" );
		list.add( "RAYÓN" );
		list.add( "RAYONES" );
		list.add( "REYNOSA" );
		list.add( "REYNOSA-MATAMOROS" );
		list.add( "ROSARIO" );
		list.add( "SABINAS" );
		list.add( "SABINAS HIDALGO" );
		list.add( "SAHUARIPA" );
		list.add( "SAHUAYO Y JIQUILPAN" );
		list.add( "SALINA CRUZ" );
		list.add( "SALTILLO" );
		list.add( "SALVATIERRA" );
		list.add( "SAN AGUSTÍN LOXICHA" );
		list.add( "SAN ANDRÉS TUXTLA" );
		list.add( "SAN BUENAVENTURA" );
		list.add( "SAN CRISTÓBAL DE LAS CASAS" );
		list.add( "SAN DIEGO DE LA UNIÓN" );
		list.add( "SAN FELIPE" );
		list.add( "SAN FELIPE" );
		list.add( "SAN FELIPE DE JESÚS" );
		list.add( "SAN FERNANDO" );
		list.add( "SAN IGNACIO" );
		list.add( "SAN ISIDRO" );
		list.add( "SAN JAVIER" );
		list.add( "SAN JOSÉ DEL CABO" );
		list.add( "SAN JOSÉ ITURBIDE" );
		list.add( "SAN JUAN BAUTISTA CUICATLAN" );
		list.add( "SAN JUAN BAUTISTA TUXTEPEC" );
		list.add( "SAN JUAN CACAHUATEPEC" );
		list.add( "SAN JUAN DE ABAJO" );
		list.add( "SAN LUIS DE LA PAZ" );
		list.add( "SAN LUIS POTOSÍ" );
		list.add( "SAN LUIS RIO COLORADO" );
		list.add( "SAN MIGUEL ALLENDE " );
		list.add( "SAN MIGUEL TLACOTEPEC" );
		list.add( "SAN NICOLÁS JACALA" );
		list.add( "SAN PABLO DEL MONTE" );
		list.add( "SAN PEDRO" );
		list.add( "SAN PEDRO DE LA CUEVA" );
		list.add( "SAN PEDRO POCHUTLA" );
		list.add( "SAN PEDRO TAPANATEPEC" );
		list.add( "SAN SEBASTIÁN TLACOLULA" );
		list.add( "SANTA ANA" );
		list.add( "SANTA BÁRBARA" );
		list.add( "SANTA CATARINA" );
		list.add( "SANTA CATARINA JUQUILA" );
		list.add( "SANTA CRUZ" );
		list.add( "SANTA CRUZ DE J. ROSAS" );
		list.add( "SANTA MARÍA IXCATLAN" );
		list.add( "SANTA ROSALÍA " );
		list.add( "SANTIAGO IXCUINTLA" );
		list.add( "SANTIAGO JAMILTEPEC" );
		list.add( "SANTIAGO JUXTLAHUACA" );
		list.add( "SANTIAGO MARAVATIO" );
		list.add( "SANTIAGO PAPASQUIARO" );
		list.add( "SANTIAGO PINOTEPA NACIONAL" );
		list.add( "SANTIAGO TUXTLA" );
		list.add( "SARIC" );
		list.add( "SASABE" );
		list.add( "SINOQUIPE" );
		list.add( "SOMBRERETE" );
		list.add( "SONOITA" );
		list.add( "SOTO LA MARINA" );
		list.add( "SOYOPA" );
		list.add( "SUAQUI GRANDE" );
		list.add( "TACAMBARO" );
		list.add( "TAMAZUNCHALE" );
		list.add( "TAMPICO" );
		list.add( "TAPACHULA" );
		list.add( "TARANDACUAO" );
		list.add( "TARIMORO" );
		list.add( "TAXCO DE ALARCÓN" );
		list.add( "TECATE" );
		list.add( "TECOMÁN" );
		list.add( "TECPAN DE GALEANA" );
		list.add( "TEHUACÁN " );
		list.add( "TEHUANTEPEC" );
		list.add( "TENOSIQUE" );
		list.add( "TEOTITLAN DE FLORES MAGÓN" );
		list.add( "TEPACHE" );
		list.add( "TEPEAPULCO" );
		list.add( "TEPIC" );
		list.add( "TIERRA BLANCA" );
		list.add( "TIJUANA" );
		list.add( "TLALTENANGO" );
		list.add( "TLAXCALA" );
		list.add( "TLAXIACO" );
		list.add( "TOLUCA" );
		list.add( "TONALÁ" );
		list.add( "TORREÓN" );
		list.add( "TULA" );
		list.add( "TULANCINGO" );
		list.add( "TUXTLA GUTIERREZ" );
		list.add( "URES" );
		list.add( "URUAPAN" );
		list.add( "VALLADOLID" );
		list.add( "VALLADOLID-TIZIMIN" );
		list.add( "VALLE DE BRAVO" );
		list.add( "VALLECILLO" );
		list.add( "VALPARAÍSO" );
		list.add( "VENUSTIANO CARRANZA" );
		list.add( "VERACRUZ" );
		list.add( "VICTORIA" );
		list.add( "VILLA FLORES" );
		list.add( "VILLA HIDALGO " );
		list.add( "VILLA PESQUEIRA" );
		list.add( "VILLAHERMOSA" );
		list.add( "VILLALDAMA-BUSTAMANTE" );
		list.add( "XALAPA" );
		list.add( "XICHU" );
		list.add( "YECORA" );
		list.add( "ZACAPU" );
		list.add( "ZACATECAS" );
		list.add( "ZACATLÁN" );
		list.add( "ZAMORA" );
		list.add( "ZARAGOZA" );
		list.add( "ZIHUATANEJO" );
		list.add( "ZINAPÉCUARO" );
		list.add( "ZITÁCUARO" );
	}
	
	public int getPopulationPk( String name ) {
		int pk = 1;
		for( String element : list ) {
			if( element.compareToIgnoreCase( name ) == 0 ) {
				return pk;
			}
			
			pk += 1;
		}
		
		return 0;
	}
}
