USE tdt;

INSERT INTO state(name, shortName, active) VALUES('AGUASCALIENTES',  'AGS', TRUE);
INSERT INTO state(name, shortName, active) VALUES('BAJA CALIFORNIA',  'B.C', TRUE);
INSERT INTO state(name, shortName, active) VALUES('BAJA CALIFORNIA SUR',  'B.C.S', TRUE);
INSERT INTO state(name, shortName, active) VALUES('CAMPECHE',  'CAMP', TRUE);
INSERT INTO state(name, shortName, active) VALUES('COAHUILA',  'COAH', TRUE);
INSERT INTO state(name, shortName, active) VALUES('COLIMA',  'COL', TRUE);
INSERT INTO state(name, shortName, active) VALUES('CHIAPAS',  'CHIS', TRUE);
INSERT INTO state(name, shortName, active) VALUES('CHIHUAHUA',  'CHIH', TRUE);
INSERT INTO state(name, shortName, active) VALUES('DISTRITO FEDERAL',  'D.F', TRUE);
INSERT INTO state(name, shortName, active) VALUES('DURANGO',  'DGO', TRUE);
INSERT INTO state(name, shortName, active) VALUES('GUANAJUATO',  'GTO', TRUE);
INSERT INTO state(name, shortName, active) VALUES('GUERRERO',  'GRO', TRUE);
INSERT INTO state(name, shortName, active) VALUES('HIDALGO',  'HGO', TRUE);
INSERT INTO state(name, shortName, active) VALUES('JALISCO',  'JAL', TRUE);
INSERT INTO state(name, shortName, active) VALUES('MÉXICO',  'MÉX', TRUE);
INSERT INTO state(name, shortName, active) VALUES('MICHOACÁN',  'MICH', TRUE);
INSERT INTO state(name, shortName, active) VALUES('MORELOS',  'MOR', TRUE);
INSERT INTO state(name, shortName, active) VALUES('NAYARIT',  'NAY', TRUE);
INSERT INTO state(name, shortName, active) VALUES('NUEVO LEÓN',  'N.L', TRUE);
INSERT INTO state(name, shortName, active) VALUES('OAXACA',  'OAX', TRUE);
INSERT INTO state(name, shortName, active) VALUES('PUEBLA',  'PUE', TRUE);
INSERT INTO state(name, shortName, active) VALUES('QUERÉTARO',  'QRO', TRUE);
INSERT INTO state(name, shortName, active) VALUES('QUINTANA ROO',  'Q.R', TRUE);
INSERT INTO state(name, shortName, active) VALUES('SAN LUIS POTOSÍ',  'S.L.P', TRUE);
INSERT INTO state(name, shortName, active) VALUES('SINALOA',  'SIN', TRUE);
INSERT INTO state(name, shortName, active) VALUES('SONORA',  'SON', TRUE);
INSERT INTO state(name, shortName, active) VALUES('TABASCO',  'TAB', TRUE);
INSERT INTO state(name, shortName, active) VALUES('TAMAULIPAS',  'TAMS', TRUE);
INSERT INTO state(name, shortName, active) VALUES('TLAXCALA',  'TLAX', TRUE);
INSERT INTO state(name, shortName, active) VALUES('VERACRUZ',  'VER', TRUE);
INSERT INTO state(name, shortName, active) VALUES('YUCATÁN',  'YUC', TRUE);
INSERT INTO state(name, shortName, active) VALUES('ZACATECAS',  'ZAC', TRUE);


INSERT INTO population(name, stateId, active) VALUES('AGUASCALIENTES', 1, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CALVILLO', 1, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ENSENADA', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ISLA DE CEDROS', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MEXICALI', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TECATE', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TIJUANA', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN FELIPE', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BAHÍA ASUNCIÓN', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BAHÍA DE TORTUGAS', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. CONSTITUCIÓN', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUERRERO NEGRO', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA PAZ', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN IGNACIO', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN ISIDRO', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JOSÉ DEL CABO', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA ROSALÍA ', 3, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CAMPECHE', 4, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. DEL CARMEN', 4, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ESCÁRCEGA', 4, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MÉXICO', 9, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. CAMARGO', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. CUAUHTÉMOC', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. DELICIAS', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. JIMÉNEZ', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. JUÁREZ', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. MADERA', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CHIHUAHUA', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HIDALGO DEL PARRAL', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OJINAGA', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN BUENAVENTURA', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NUEVO CASAS GRANDES', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA BÁRBARA', 8, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARRIAGA', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARRIAGA - TONALÁ', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BENEMÉRITO DE LAS AMÉRICAS', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CINTALAPA DE FIGUEROA', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('COMITÁN DE DOMÍNGUEZ', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('EL TRIUNFO', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MARQUES DE COMILLAS', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MOTOZINTLA', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OCOSINGO', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PALENQUE', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PIJIJIAPAN', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PICHUCALCO', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN CRISTÓBAL DE LAS CASAS', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TAPACHULA', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TONALÁ', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TUXTLA GUTIERREZ', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VENUSTIANO CARRANZA', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VILLA FLORES', 7, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. ACUÑA', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. ALLENDE', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MONCLOVA', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NUEVA ROSITA', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PARRAS DE LA FUENTE', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PIEDRAS NEGRAS', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SABINAS', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SALTILLO', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TORREÓN', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TORREÓN ', 5, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARMERÍA', 6, TRUE);
INSERT INTO population(name, stateId, active) VALUES('COLIMA', 6, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ISLA SOCORRO', 6, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MANZANILLO', 6, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TECOMÁN', 6, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CUENCAME', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DURANGO', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GÓMEZ PALACIO', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUADALUPE VICTORIA', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO PAPASQUIARO', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN PEDRO', 10, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ACAPULCO', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CHILPANCINGO', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('IGUALA', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('IXTAPA-ZIHUATANEJO', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OMETEPEC', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TAXCO DE ALARCÓN', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TECPAN DE GALEANA', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZIHUATANEJO', 12, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ACÁMBARO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ATARJEA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CELAYA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CORONEO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('COMONFORT', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DR. MORA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DOLORES HIDALGO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUANAJUATO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUANÍMARO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('JERÉCUARO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LEÓN', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OCAMPO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PÉNJAMO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SALVATIERRA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN DIEGO DE LA UNIÓN', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN FELIPE', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JOSÉ ITURBIDE', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN LUIS DE LA PAZ', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN MIGUEL ALLENDE ', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA CATARINA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA CRUZ DE J. ROSAS', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO MARAVATIO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TARANDACUAO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TARIMORO', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TIERRA BLANCA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VICTORIA', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('XICHU', 11, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUEJUTLA DE REYES', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('IXMIQUILPAN', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PACHUCA', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TULA', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TULANCINGO', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEPEAPULCO', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN NICOLÁS JACALA', 13, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ATOTONILCO EL ALTO', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('AUTLÁN DE NAVARRO', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. GUZMÁN', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CERRO LOS TENAMASTES', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUADALAJARA', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUADALAJARA ', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA BARCA', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PUERTO VALLARTA', 14, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ALTZOMONI', 15, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CERRO PICO TRES PADRES', 15, TRUE);
INSERT INTO population(name, stateId, active) VALUES('JOCOTITLAN', 15, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TOLUCA', 15, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VALLE DE BRAVO', 15, TRUE);
INSERT INTO population(name, stateId, active) VALUES('APATZINGÁN', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. HIDALGO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('JIQUILPAN DE JUÁREZ', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA PIEDAD', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LÁZARO CÁRDENAS', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOS REYES SALGADO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MORELIA', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PÁTZCUARO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PURUANDIRO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAHUAYO Y JIQUILPAN', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TACAMBARO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('URUAPAN', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZACAPU', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZAMORA', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZITÁCUARO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZITACUARO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZINAPÉCUARO', 16, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CUERNAVACA', 17, TRUE);
INSERT INTO population(name, stateId, active) VALUES('AGUALEGUAS', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ANÁHUAC', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARAMBERRI', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CADEREYTA-MONTERREY', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CERRALVO-MELCHOR OCAMPO', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DR. ARROYO', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DR. COSS', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GRAL. BRAVO-GRAL. TAPIA', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GRAL. TREVIÑO', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HIGUERAS', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ITURBIDE', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA CHONA- ARAMBERRI', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LAMPAZOS', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LINARES', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOS ALDAMAS-ESTACIÓN LOS ALDAMA', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOS HERRERA', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOS RAMONES', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MIER Y NORIEGA', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MONTERREY', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PARAS', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('RAYONES', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SABINAS HIDALGO', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VALLECILLO', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VILLALDAMA-BUSTAMANTE', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZARAGOZA', 19, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ACAPONETA Y TECUALA', 18, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ISLAS MARÍAS', 18, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JUAN DE ABAJO', 18, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO IXCUINTLA', 18, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEPIC', 18, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ACATLÁN DE PÉREZ FIGUEROA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ASUNCIÓN  NOCHISTLAN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CONCEPCIÓN PÁPALO', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CORRAL DE PIEDRA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUAJUAPAN DE LEÓN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUAUTLA DE JIMÉNEZ', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('JUCHITÁN DE ZARAGOZA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOMA BONITA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MATÍAS ROMERO', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MIAHUATLÁN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OAXACA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PALMA SOLA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PUERTO ÁNGEL', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PUERTO ESCONDIDO', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SALINA CRUZ', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN AGUSTÍN LOXICHA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JUAN BAUTISTA CUICATLAN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JUAN BAUTISTA TUXTEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JUAN CACAHUATEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN MIGUEL TLACOTEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN PEDRO POCHUTLA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN PEDRO TAPANATEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN SEBASTIÁN TLACOLULA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA CATARINA JUQUILA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA MARÍA IXCATLAN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO JAMILTEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO JUXTLAHUACA', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO PINOTEPA NACIONAL', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEHUANTEPEC', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEOTITLAN DE FLORES MAGÓN', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TLAXIACO', 20, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PUEBLA', 21, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEHUACÁN ', 21, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZACATLÁN', 21, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CHETUMAL', 23, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CANCÚN', 23, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CHETUMAL', 23, TRUE);
INSERT INTO population(name, stateId, active) VALUES('COZUMEL', 23, TRUE);
INSERT INTO population(name, stateId, active) VALUES('FELIPE CARRILLO PUERTO', 23, TRUE);
INSERT INTO population(name, stateId, active) VALUES('QUERÉTARO', 22, TRUE);
INSERT INTO population(name, stateId, active) VALUES('QUERETARO', 22, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. VALLES', 24, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MATEHUALA', 24, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN LUIS POTOSÍ', 24, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TAMAZUNCHALE', 24, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CULIACÁN', 25, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LOS MOCHIS', 2, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MAZATLÁN', 25, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ADIVINO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('AGUA PRIETA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ÁLAMOS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARIVECHI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ARIZPE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ATIL', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BACADEHUACHI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BACANORA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BACERAC', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BACOACHI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BANAMICHI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BAVIACORA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BAVISPE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('BENJAMÍN HILL', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CABORCA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CANANEA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CARBO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. OBREGÓN', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CUCURPE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CUMPAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('DIVISADERO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('FRONTERAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GRANADOS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('GUAYMAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HERMOSILLO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUACHINERAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUASABAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('IMURIS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MAGDALENA DE KINO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MAZATAN', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MOCTEZUMA ', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NACO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NACORI CHICO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NACORI GRANDE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NACOZARI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NAVOJOA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NOGALES', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ONAVAS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('OQUITOA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PUERTO PEÑASCO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('QUEROBABI', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('RAYÓN', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ROSARIO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAHUARIPA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN FELIPE DE JESÚS', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN JAVIER', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN LUIS RIO COLORADO', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN PEDRO DE LA CUEVA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA ANA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTA CRUZ', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SARIC', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SASABE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SINOQUIPE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SONOITA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SOYOPA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SUAQUI GRANDE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TEPACHE', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('URES', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VILLA HIDALGO ', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VILLA PESQUEIRA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('YECORA', 26, TRUE);
INSERT INTO population(name, stateId, active) VALUES('FRONTERA', 27, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA VENTA', 27, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TENOSIQUE', 27, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VILLAHERMOSA', 27, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. MANTE', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CD. VICTORIA', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LA ROSITA - VILLAGRÁN', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MATAMOROS', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NUEVO LAREDO', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('REYNOSA', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('REYNOSA-MATAMOROS', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN FERNANDO', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SOTO LA MARINA', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TAMPICO', 28, TRUE);
INSERT INTO population(name, stateId, active) VALUES('APIZACO', 29, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CALPULALPAN', 29, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUAMANTLA', 29, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN PABLO DEL MONTE', 29, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TLAXCALA', 29, TRUE);
INSERT INTO population(name, stateId, active) VALUES('CERRO AZUL', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('COATZACOALCOS', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('HUAYACOCOTLA', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('IXHUATLAN DE MADERO', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('LAS LAJAS', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VERACRUZ', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MECAYAPAN', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ORIZABA', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('PEROTE', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SANTIAGO TUXTLA', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SAN ANDRÉS TUXTLA', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('XALAPA', 30, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MERIDA', 31, TRUE);
INSERT INTO population(name, stateId, active) VALUES('MÉRIDA', 31, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VALLADOLID', 31, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VALLADOLID-TIZIMIN', 31, TRUE);
INSERT INTO population(name, stateId, active) VALUES('FRESNILLO', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('JALPA', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('NOCHISTLÁN', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('SOMBRERETE', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('TLALTENANGO', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('VALPARAÍSO', 32, TRUE);
INSERT INTO population(name, stateId, active) VALUES('ZACATECAS', 32, TRUE);


INSERT INTO concessionaire(name, active) VALUES('CANAL 13 DE MICHOACÁN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('CANALES DE TELEVISIÓN POPULARES, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('CANALES DE TELEVISIÓN POPULARES, S.A. DE C.V. ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('COMITÉ PRO-ANTENA PARABÓLICA DE MONCLOVA, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('COMPAÑÍA INTERNACIONAL DE RADIO Y TELEVISIÓN, S.A.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('COMUNICACIÓN 2000, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('COMUNICACIÓN DEL SURESTE, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('CONGRESO GENERAL DE LOS ESTADOS UNIDOS MEXICANOS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('CORPORACIÓN TAPATÍA DE TELEVISIÓN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('FLORES Y FLORES, S. EN N.C. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('FOMENTO EDUCATIVO Y CULTURAL FRANCISCO DE IBARRA, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('FUNDACIÓN CULTURAL POR ZACATECAS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL DISTRITO FEDERAL', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE AGUASCALIENTES', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE BAJA CALIFORNIA SUR', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE CAMPECHE', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE CHIAPAS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE COLIMA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE GUANAJUATO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE GUERRERO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE HIDALGO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE JALISCO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE MÉXICO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE MICHOACÁN', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE MORELOS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE NAYARIT', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE NUEVO LEÓN', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE OAXACA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE PUEBLA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE QUINTANA ROO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE SAN LUIS POTOSÍ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE SONORA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE TLAXCALA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE VERACRUZ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('GOBIERNO DEL ESTADO DE ZACATECAS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('HILDA GRACIELA RIVERA FLORES', TRUE);
INSERT INTO concessionaire(name, active) VALUES('INSTITUTO POLITÉCNICO NACIONAL', TRUE);
INSERT INTO concessionaire(name, active) VALUES('INTEGRACIÓN MEXICANA CON VISIÓN EN ZACATECAS, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('INTERMEDIA Y ASOCIADOS DE MEXICALI, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('JAIME JUARISTI SANTOS', TRUE);
INSERT INTO concessionaire(name, active) VALUES('JOSÉ DE JESÚS PARTIDA VILLANUEVA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('JOSÉ HUMBERTO Y LOUCILLE, MARTÍNEZ MORALES', TRUE);
INSERT INTO concessionaire(name, active) VALUES('LUCIA PÉREZ MEDINA VDA. DE MONDRAGÓN', TRUE);
INSERT INTO concessionaire(name, active) VALUES('MARIO ENRÍQUEZ MAYANS CONCHA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('MULTIMEDIOS TELEVISIÓN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('PATRO. PARA INST. REPET. CANALES DE T.V., COATZ., VER., A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('PATRONATO DE TELEVISIÓN CULTURAL DE GUANAJUATO, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('PATRONATO PRO-TELEVISIÓN DE COZUMEL, A. C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('PEDRO LUIS FITZMAURICE MENESES', TRUE);
INSERT INTO concessionaire(name, active) VALUES('PROYECCIÓN CULTURAL SANMIGUELENSE, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('RADIO TELEVISIÓN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('RADIOTELEVISORA DE MÉXICO NORTE, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('RADIOTELEVISORA DE MÉXICO NORTE, S.A. DE C.V. ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('RAMONA ESPARZA GONZÁLEZ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('ROBERTO CASIMIRO GONZÁLEZ TREVIÑO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('SISTEMA ESTATAL DE COMUNICACIÓN CULTURAL Y EDUCATIVA DEL GOBIERNO DE QUERÉTARO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('SISTEMA PÚBLICO DE RADIODIFUSIÓN DEL ESTADO MEXICANO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('SISTEMA REGIONAL DE TELEVISIÓN, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('SISTEMA TELE YUCATÁN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('T.V. DE CULIACÁN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('T.V. DE LOS MOCHIS, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELE NACIONAL S. DE R.L. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELE-EMISORAS DEL SURESTE, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEIMAGEN DEL NOROESTE, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEMISIÓN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELESISTEMAS DE COAHUILA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVIMEX, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVIMEX, S.A. DE C.V. ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN AZTECA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DE LA FRONTERA, S.A.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DE MICHOACÁN, S.A. DE C.V. ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DE PUEBLA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DE TABASCO, S.A.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DEL PACIFICO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN DIGITAL, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN LA PAZ, S.A.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN METROPOLITANA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN TABASQUEÑA, S.A. DE C.V.                                                            ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISIÓN TABASQUEÑA, S.A. DE C.V.                                                             ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA ALCO, S. DE R.L. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE CANCÚN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE DURANGO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE HERMOSILLO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE MEXICALI, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE MEXICALI, S.A. DE C.V. ', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE NAVOJOA, S.A.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE OCCIDENTE, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DE YUCATÁN, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DEL VALLE DE MÉXICO, S.A.P.I. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA DEL YAQUI, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA FRONTERIZA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA NACIONAL, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA PENINSULAR, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA POTOSINA, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TELEVISORA XHBO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TV DIEZ DURANGO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TV OCHO, S.A. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('TVNORTE, S. DE  R.L. DE C.V.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD AUTÓNOMA DE NUEVO LEÓN', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD AUTÓNOMA ESPAÑA DE DURANGO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD DE GUADALAJARA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD DE SONORA', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD JUÁREZ AUTÓNOMA DE TABASCO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD JUÁREZ DEL ESTADO DE DURANGO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO', TRUE);
INSERT INTO concessionaire(name, active) VALUES('VALORES Y TRADICIONES DE MI TIERRA, A.C.', TRUE);
INSERT INTO concessionaire(name, active) VALUES('XHFJS-TV, S.A. DE C.V.', TRUE);


INSERT INTO concessionType(type, description, active) VALUES('(C)', 'CONCESIÓN', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(P)', 'PERMISO', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(C)*', 'CONCESIÓN (EN PROCESO DE INSTALACIÓN)', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(P)*', 'PERMISO (EN PROCESO DE INSTALACIÓN)', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(CP)*', 'PERMISO (EN PROCESO DE INSTALACIÓN)', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(CS)*', 'PERMISO (EN PROCESO DE INSTALACIÓN)', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(CP)**', 'PERMISO (SUJETO A NOTIFICACIÓN)', TRUE);
INSERT INTO concessionType(type, description, active) VALUES('(CS)**', 'PERMISO (SUJETO A NOTIFICACIÓN)', TRUE);


INSERT INTO channelBand(name, description, active) VALUES('TV', 'ANÁLOGO', TRUE);
INSERT INTO channelBand(name, description, active) VALUES('TDT', 'DIGITAL', TRUE);



INSERT INTO channel(distinctive, name, virtualChannel, physicChannel, quality, resolution, power, acesli, longitude, latitude, effectiveDateStart, effectiveDateEnd, channelBandId, populationId, concessionaireId, concessionTypeId, active) VALUES
('XHGC', 'CANAL 5', 5.1, 35, 'HD', '1080i', 225, 34, '33.33', '44.33', '2000-03-12', '2030-03-12', 2, 204, 67, 1, TRUE);
INSERT INTO channel(distinctive, name, virtualChannel, physicChannel, quality, resolution, power, acesli, longitude, latitude, effectiveDateStart, effectiveDateEnd, channelBandId, populationId, concessionaireId, concessionTypeId, active) VALUES
('XHIH', 'AZTECA 7', 7.1, 30, 'SD', '480i', 200, 50, '43.33', '54.33', '2002-11-01', '2032-11-01', 1, 184, 69, 2, TRUE);
INSERT INTO channel(distinctive, name, virtualChannel, physicChannel, quality, resolution, power, acesli, longitude, latitude, effectiveDateStart, effectiveDateEnd, channelBandId, populationId, concessionaireId, concessionTypeId, active) VALUES
('XHAOX', 'IMAGEN TV', 3.1, 26, 'SD', '480i', 215, 25, '23.33', '34.33', '2016-11-25', '2046-11-25', 2, 190, 64, 3, TRUE);


INSERT INTO channel(populationId, concessionTypeId, concessionaireId, distinctive,
					channelBandId, physicChannel, virtualChannel, power, latitude,
					longitude, acesli, effectiveDateStart, effectiveDateEnd, quality,
					resolution, name, active) 
VALUES()
