CREATE DATABASE IF NOT EXISTS tdt
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;
USE tdt;

CREATE TABLE IF NOT EXISTS state(
	stateId TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25),
	shortName VARCHAR(5),
	active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS population(
	populationId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50),
	stateId TINYINT NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY (stateId) REFERENCES state(stateId)
);

CREATE TABLE IF NOT EXISTS concessionaire(
	concessionaireId SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100),
	active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS concessionType(
	concessionTypeId TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(25) NOT NULL,
	description VARCHAR(40) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS channelBand(
	channelBandId TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(3) NOT NULL,
	description VARCHAR(10) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS channel(
	channelId SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	distinctive VARCHAR(8) NOT NULL,
	name VARCHAR(50) NOT NULL DEFAULT 'N/A',
	virtualChannel FLOAT(3,1) NOT NULL DEFAULT 0.0,
	physicChannel TINYINT NOT NULL,
	quality VARCHAR(2) NOT NULL DEFAULT 'SD',
	resolution VARCHAR(5) NOT NULL DEFAULT '480i',
	power FLOAT(10,3) NOT NULL,
	acesli SMALLINT NOT NULL,
	longitude VARCHAR(15) NOT NULL,
	latitude VARCHAR(15) NOT NULL,
	effectiveDateStart VARCHAR(60) NOT NULL,
	effectiveDateEnd VARCHAR(60) NOT NULL,
	channelBandId TINYINT NOT NULL,
	populationId INT NOT NULL,
	concessionaireId SMALLINT NOT NULL,
	concessionTypeId TINYINT NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY (channelBandId) REFERENCES channelBand(channelBandId),
	FOREIGN KEY (populationId) REFERENCES population(populationId),
	FOREIGN KEY (concessionaireId) REFERENCES concessionaire(concessionaireId),
	FOREIGN KEY (concessionTypeId) REFERENCES concessionType(concessionTypeId)
);

